[package]
name = "ed25519_dalek_wasm"
version = "1.0.0"
authors = ["hazae41 <hazae41@proton.me>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.63"
wee_alloc = "0.4.5"
js-sys = "0.3"
ed25519 = "1.0.3"
ed25519-dalek = "1.0.1"
rand = { version = "0.7.3", features = ["wasm-bindgen"] }