[package]
name = "berith"
version = "1.0.0"
authors = ["hazae41 <hazae41@proton.me>"]
edition = "2021"

description = "WebAssembly port of Dalek's Ed25519, a Rust implementation of Ed25519 signatures"
repository = "https://github.com/hazae41/ed25519-dalek-wasm"
license = "Unlicense"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
debug = false
opt-level = 3

[dependencies]
wasm-bindgen = { version = "0.2.83", default-features = false }
ed25519-dalek = { version = "1.0.1", default-features = false, features = ["rand", "u64_backend"] }
rand = { version = "0.7.3", default-features = false, features = ["wasm-bindgen", "getrandom"] }