[package]
name = "ed25519_dalek_wasm"
version = "1.0.0"
authors = ["hazae41 <hazae41@proton.me>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
debug = false
opt-level = 3

[dependencies]
wasm-bindgen = { version = "0.2.83", default-features = false }
wee_alloc = { version = "0.4.5", default-features = false, features = ["size_classes"] }
ed25519-dalek = { version = "1.0.1", default-features = false, features = ["rand", "u64_backend"] }
rand = { version = "0.7.3", default-features = false, features = ["wasm-bindgen", "getrandom"] }