/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function x25519staticsecret_random(): number;
export function x25519staticsecret_from_bytes(a: number, b: number, c: number): void;
export function x25519staticsecret_diffie_hellman(a: number, b: number): number;
export function x25519staticsecret_to_public(a: number): number;
export function ed25519verifyingkey_from_bytes(a: number, b: number, c: number): void;
export function ed25519verifyingkey_to_bytes(a: number, b: number): void;
export function ed25519verifyingkey_verify(a: number, b: number, c: number, d: number): number;
export function x25519publickey_from_bytes(a: number, b: number, c: number): void;
export function x25519publickey_to_bytes(a: number, b: number): void;
export function x25519sharedsecret_was_contributory(a: number): number;
export function __wbg_ed25519signature_free(a: number): void;
export function ed25519signature_from_bytes(a: number, b: number, c: number): void;
export function ed25519signature_to_bytes(a: number, b: number): void;
export function ed25519signingkey_new(): number;
export function ed25519signingkey_from_bytes(a: number, b: number, c: number): void;
export function ed25519signingkey_to_bytes(a: number, b: number): void;
export function ed25519signingkey_public(a: number): number;
export function ed25519signingkey_sign(a: number, b: number, c: number): number;
export function ed25519verifyingkey_new(a: number, b: number, c: number): void;
export function x25519publickey_new(a: number, b: number, c: number): void;
export function ed25519signature_new(a: number, b: number, c: number): void;
export function ed25519signingkey_random(): number;
export function x25519staticsecret_to_bytes(a: number, b: number): void;
export function x25519sharedsecret_to_bytes(a: number, b: number): void;
export function __wbg_x25519staticsecret_free(a: number): void;
export function __wbg_x25519publickey_free(a: number): void;
export function __wbg_x25519sharedsecret_free(a: number): void;
export function __wbg_ed25519verifyingkey_free(a: number): void;
export function __wbg_ed25519signingkey_free(a: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
